version: '3.6'

services:

  pg:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:5432

  {{cookiecutter.app_slug}}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './{{cookiecutter.app_slug}}:/usr/src/app/{{cookiecutter.app_slug}}'
    ports:
      - 8001:8001
    environment:
      - PORT=4488
      - SQLALCHEMY_DATABASE_URI=postgresql://hydra_login2f_service:hydra_login2f_service@pg/${POSTGRES_DB}
    command: develop
    depends_on:
      - pg
